<script src= "views/js/seat_selector.js"></script>
<script src= "views/js/jquery.seat-charts.min.js"></script>

<link 	rel="stylesheet" 
		href="views/css/jquery.seat-charts.css">
		
<div class= 'title'> Asientos </div>
<div id= 'seleccionDeAsientos'></div>

<div id="seat-map" class= "seatsImage">
	  <div class="front-indicator">En frente</div>
</div>

<div class="booking-details">
	  <h2>Detalles de los pasajeros</h2>

	  <ul id="selected-seats">
	  </ul>
	  
	  <button class="checkout-button">Continuar &raquo;</button>

	  <div id="legend"></div>
