<!DOCTYPE html>

<html>
	<head>
		<title>AeroAlpes Template</title>
	</head>

<body>

<div class='title'>
		Check-In
</div>

<div id="contCheck">

		<div id="datos" >
			<span style= 'font-size: 18px;'>Ingresa tus datos</span>
			<hr>

			<label for="numBoleto">Número de boleto</label>
			<div class="input-group mb-1">
					<input type="text" name="numBoleto" class="form-control" placeholder="#">
			</div>

			<br>
			<br>
			<button type="button" class="btn btn-primary btn-sm">Continuar&nbsp;&nbsp;&#x25b6;</button>

		</div>

		<div class="pase">
			<img style= 'width: 70%' src="views/img/pase.png" alt="pase">
			<br><br>
			Consigue tu pase de abordar electronico para ahorrar tiempo
		</div>

</div>

</body>
</html>
