<script type= "text/javascript" 
		src= "views/js/checkin.js">
</script>

<div class='title'>
	Check-In
</div>

<div id="contCheck">
		<form id="datos">
			<span style= 'font-size: 18px;'>Ingresa tus datos</span>
			<hr>
			<br>
			<label for="noBoleto">Número de boleto
				<input id= "noBoleto" type="text" name="numBoleto" placeholder="#">
			</label>
			<button type="submit" class="btnSearch" >Continuar&nbsp;&nbsp;&#x25b6;</button>

		</form>

		<div class="pase">
			<img src="views/img/pase.png" alt="pase">
			<br><br>
			Consigue tu pase de abordar electronico para ahorrar tiempo
		</div>

</div>
