<!doctype html>
<html>

<head>	
	<link 	rel= "stylesheet"  
			type= "text/css" 
			href= "views/css/carousel.css">
	<script type= "text/javascript" 
			src= "views/js/carousel.js"></script>
		
	<script type= "text/javascript" 
			src= "views/js/home.js"></script>
		
</head>

<body>
	
	<div id="srchForm">
		<form action= "views/Vuelos.phtml" method= "post" id= "flyOptions">
			 <label for= "tipo">Tipo<br>
			 
			 	<select name= "tipo" >
					<option value="Sencillo">Sencillo</option>
					<option value="Redondo">Redondo</option>			
				</select>

			 </label>

			  <label for= "origen">Origen<br>
			  	<select name= "origen" >
					<?php
				  	foreach ($origins as $origin) 
					{
    					echo '<option value="'.$origin["origen"].'">'.iconv('latin1', 'UTF-8//IGNORE', $origin["origen"]).'</option>';
					}
				  	?>		
				</select>
					
			 </label>

			 <label for= "destino">Destino<br>
			 	<select name= "destino" >
					<?php
				  	foreach ($destins as $destin) {
    					echo '<option value="'.$destin["destino"].'">'.iconv('latin1', 'UTF-8//IGNORE', $destin["destino"]).'</option>';
						
					}
				  	?>		
				</select>
			 </label>

			 <label for= "pasajeros">
				Pasajeros
				<br><input type="text" id="opPasajeros" onclick="showPass(this);" onFocus="hidePass();" name= "pasajeros"> 
			
				<div id="pax" style="display:none;">
					
					<span>Adultos<br>
						<button id='subAdult' name = 'radButton'>-</button>
							<label id='lbAdult'>0</label>
						<button id='addAdult' name = 'radButton'>+</button>
					</span>
					
					<span>Menores <br>
						<button id='subKid' name = 'radButton'>-</button>
							<label id='lbKid'>0</label>
						<button id='addKid' name = 'radButton'>+</button>
					</span>
					
					<span>Bebes <br>
						<button id='subBaby' name = 'radButton'>-</button>
							<label id='lbBaby'>0</label>
						<button id='addBaby' name = 'radButton'>+</button>
					</span>

				</div>
				
 			 </label>
 			 
			 <label for= "clase">
				Clase
				<br><select name= "clase" >
					<option value= "vip">VIP</option>
					<option value= "Ejecutivo">Ejecutivo</option>		
					<option value= "Turista">Turista</option>		
					</select>

			 </label>

			  <label for="fechaSal">
				 Fecha de Salida
				 <br><input name= "fechaSal" type="text" id="opFechaSal" > 
			 </label>

			  <label for= "fechaReg">
				 Fecha de Regreso
				 <br><input name= "fechaReg" type="text" id="opFechaReg" > 
			 </label>

		</form>

		<input type= "submit" form= "flyOptions" class= "btnSearch">Buscar Vuelos &nbsp;&nbsp;&#x25b6;</input>
		
	</div>
	
	<p class="bigText">¡Descubre!</p>
		
	<div id="wrapper_bu">
	
		<div id="bu1"><p class="txt_Center txt_h1">1</p></div>
		<div id="bu2"><p class="txt_Center txt_h1">2</p></div>
		<div id="bu3"><p class="txt_Center txt_h1">3</p></div>
		<div id="bu4"><p class="txt_Center txt_h1">4</p></div>
		<div id="bu5"><p class="txt_Center txt_h1">5</p></div>
			
	</div>
	

</body>


</html>