<link href="css/styles.css" rel="stylesheet" type="text/css">

<form id="formPay">
	<span>
		 <label style="width: 50%" for="price">
				Precio
			<input style="width: 50%;" name= "price" type="text" id="price" placeholder="$" readonly> 
		</label>
	</span>
	 
	<span>
		<label id="info">
		<span class= "trn">Ingrese sus datos</span>
		</label>
	</span>
		 
	<span> 
		<label for="firstName">
				<span class= "trn">Nombre</span>
			<input name= "firstName" type="text" id="firstName"> 
		</label>

		<label for="lastName">
				<span class= "trn">Apellidos</span>
			<input  name= "lastName" type="text" id="lastName"> 
		</label>
	</span>
	 
		 <br>
	<span>
		<label style="width: 50%" for="cc">
				<span class= "trn">Número de tarjeta</span><br>
			<input style="width: 100%;" name= "cc" type="text" id="cc" placeholder="#"> 
		</label>
	</span>
	
	<span>
		<label for="date">
				<span class= "trn">Expiración</span>
			<input style="width: 15%;"  name= "month" type="text" id="month" placeholder="Mes"> 
				/
			<input style="width: 15%;" name= "year" type="text" id="year" placeholder="Año"> 
				<span class= "trn">CVV</span>
			<input style="width: 10%;" name= "CVV" type="text" id="CVV" placeholder="###"> 	
		</label>
	</span>
	
	<button type= "button" class= "btnSIA" style="float: right;" onclick= "pay();"><span class= "trn">Pagar</span> &nbsp; &#x25b6; </button>
		 
</form>
