<!doctype html>
<div id= 'procesadorDePagos'>
	<form id="formPay">
		<div>
			 <label style="width: 50%" for="price">
					<span class= "trn">Precio Total</span>
				<input style="width: 50%;" name= "price" type="text" id="price" placeholder="$" readonly> 
			</label>
		</div>
		 
		<div>
			<label id="info">
			<span class= "trn">Ingrese sus datos</span>
			</label>
		</div>
			 
		<div> 
			<label for="firstName">
					<span class= "trn">Nombre</span>
				<input name= "firstName" type="text" id="firstName"> 
			</label>

			<label for="lastName">
					<span class= "trn">Apellidos</span>
				<input  name= "lastName" type="text" id="lastName"> 
			</label>
		</div>
		 
	
		<div>
			<label style="width: 50%" for="cc">
					<span class= "trn">Número de tarjeta</span><br>
				<input style="width: 100%;" name= "cc" type="text" id="cc" placeholder="#"> 
			</label>
		</div>
		
		<div>
			<label for="date">
					<span class= "trn">Expiración</span>
				<input style="width: 15%;"  name= "month" type="text" id="month" placeholder="Mes"> 
					/
				<input style="width: 15%;" name= "year" type="text" id="year" placeholder="Año"> 
					<span class= "trn">CVV</span>
				<input style="width: 10%;" name= "CVV" type="text" id="CVV" placeholder="###"> 	
			</label>
		</div>
		<div>
			<label style="width: 30%" for="tel">
					<span class= "trn">Telefono</span><br>
				<input style="width: 100%;" name= "tel" type="text" id="tel" placeholder="#"> 
			</label>
		</div>
		
		<button type= "button" class= "btnSIA" style="float: right;margin:0px;" onclick= "pay();"><span class= "trn">Pagar</span> &nbsp; &#x25b6; </button>
	</form>
</div>
<script>document.getElementById("price").value = document.getElementById("total").innerText;</script>