<?php

function ticketChecked(){
	echo <<<EOT
	<p>Presiona para confirmar su boleto No: {$_GET['numBoleto']} 
	<br>se enviará el pase de abordar a su correo
	<br>{$_GET['email']}</p>
	
	<button type="button" class="btnTransparent" onclick="confirm();" style="width:150px" >	
		<img style="width:100%" src="views/img/check.png" alt="check" title="¡Click para Confirmar!">	
	</button><br>
	
	<button type="button" class="btnSIA" onclick="solicitar('views/Checkin.phtml');">
		ó regresar &nbsp; ▶
	</button>
				
EOT;
}

function ticketError(){
	echo <<<EOT
	<img style="width:100px" src="views/img/error.png" alt="check">	
	
	<p>No se ha encontrado su boleto con el número: {$_GET["numBoleto"]} </p>
	
	<button type="button" class="btnSIA" onclick="solicitar('views/Checkin.phtml');">
		Reintentar &nbsp; ▶
	</button>
	
EOT;
}

function successConfirm(){
	return <<<EOT
	<p>Su boleto No: {$_GET["numBoleto"]} a sido confirmado
	<br>se ha enviado el pase de abordar a su correo
	<br>{$_GET['email']}</p>
	
	<img style="width:150px" src="views/img/pase.png" alt="check"><br>
	
	<button type="button" class="btnSIA" onclick="solicitar('views/Checkin.phtml');">
		Regresar &nbsp; ▶
	</button>
				
EOT;
}

function errorConfirm(){
	echo <<<EOT
	<img style="width:100px" src="views/img/error.png" alt="check">	
	
	<p>Lo sentimos no hemos confirmar su boleto con el número: {$_GET["numBoleto"]} 
	<br>Contacte al servicio a clientes de AeroAlpes</p>
	
	<button type="button" class="btnSIA" onclick="solicitar('views/Checkin.phtml');">
		Regresar &nbsp; ▶
	</button>
	
EOT;
}

function htmlEmail(){
ob_start(); 
require $_SERVER['DOCUMENT_ROOT']."/views/emailBoard.phtml"; 
$contents = ob_get_contents(); 
ob_end_clean(); 

return $contents; // the output of the included file 

}

?>
